services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app/
      - /app/.venv
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
